name = "domislink-admin"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[env.production]
NODE_ENV = "production"

[env.production.vars]
NEXT_PUBLIC_APP_URL = "https://admin.domislink.com"